# Generated by Django 5.1.3 on 2024-11-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_remove_task_created_at_alter_task_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='name',
        ),
        migrations.RemoveField(
            model_name='column',
            name='order',
        ),
        migrations.AddField(
            model_name='column',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
